#!/usr/bin/env node
// Reads src/wasm/fir.wasm and writes src/dsp/wasm-binary.ts with the bytes
// embedded as a Uint8Array literal. Run after compiling the AssemblyScript source.

import { readFileSync, writeFileSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

function readBytes(file) {
  return Array.from(readFileSync(join(root, file))).join(",");
}

const output = `\
// Copyright 2026 Jacobo Tarrio Barreiro. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// AUTOGENERATED -- do not edit.
// Rebuild with npm run build:wasm

export const CONVOLVER = new Uint8Array([${readBytes("src/wasm/convolver.wasm")}]);
export const FFT = new Uint8Array([${readBytes("src/wasm/fft.wasm")}]);
`;

writeFileSync(join(root, "src/wasm/wasm-bytes.ts"), output);
