#!/usr/bin/env node
// Reads src/wasm/fir.wasm and writes src/dsp/wasm-binary.ts with the bytes
// embedded as a Uint8Array literal. Run after compiling the AssemblyScript source.

import { readFileSync, writeFileSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

function readBytes(file) {
  return Array.from(readFileSync(join(root, file))).join(",");
}

const output = `\
// AUTOGENERATED -- do not edit.
// Rebuild with npm run build:wasm

export const CONVOLVER = new Uint8Array([${readBytes("src/wasm/convolver.wasm")}]);
export const FFT = new Uint8Array([${readBytes("src/wasm/fft.wasm")}]);
`;

writeFileSync(join(root, "src/wasm/wasm-bytes.ts"), output);
