#!/usr/bin/env node
// Reads src/wasm/fir.wasm and writes src/dsp/wasm-binary.ts with the bytes
// embedded as a Uint8Array literal. Run after compiling the AssemblyScript source.

import { readFileSync, writeFileSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";


const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const convolver = Array.from(readFileSync(join(root, "src/wasm/convolver.wasm"))).join(",");

const output = `\
// AUTOGENERATED -- do not edit.
// Rebuild with npm run build:wasm

export const CONVOLVER = new Uint8Array([${convolver}]);
`;

writeFileSync(join(root, "src/wasm/wasm-bytes.ts"), output);
